export const ADD_CONTACT = 'ADD_CONTACT'
export const GET_CONTACTS = 'GET_CONTACTS'
export const DET_CONTACT = 'DET_CONTACT'
export const GET_CONTACT = 'GET_CONTACT'
export const UPD_CONTACT = 'UPD_CONTACT'
export const PAGINATION = 'PAGINATION'